---
- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Template the HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: Enable and start HAProxy service
  systemd:
    name: haproxy
    enabled: yes
    state: started

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

